pipeline {
    agent any
    environment {
        PATH = "/usr/local/bin:${env.PATH}"
    }
    stages {
        stage('Test Docker') {
            steps {
                sh 'docker --version'
            }
        }
    }
}

