pipeline {
    agent {
        docker {
            image 'nginx:alpine'
            args '-p 8090:80'
        }
    }
    stages {
        stage('Serve Hello World') {
            steps {
                script {
                    // Copy the index.html into the Nginx container's default web root
                  
                  sh 'sudo chown -R root:root /usr/share/nginx/html'
                  sh 'sudo cp -f simple-nginx-project/index.html /usr/share/nginx/html/index.html'
                }
                // Run Nginx container and serve the content
                  sh 'nginx -g "daemon off;"'
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}

