pipeline {

  agent {
    docker {
      image 'maven:3.8.6-openjdk-11'
      args '-v /root/.m2:/root/.m2' //optional: to checkmaven dependencies
}
}
stages {
  stage('Checkout') {
    steps {
      git branch: 'main', 
        url: 'https://github.com/bimal-root/Jenkins-Zero-To-Hero.git'
} 
}
  stage('Verify') {
    steps {
      sh 'ls -l'
}
}

  stage('Build') {
    steps {
    // build mvn project
      sh 'mvn -f /Jenkins-Zero-To-Hero/html-maven-project/html-maven-project/pom.xml clean package'
}
}
  stage('Run') {
    steps {
   // start maven server to serve html file by using maven jetty plugin or Tomcat:
      sh 'mvn jetty:run'
}
}
}
post {
  always {
	// clean up
    cleanWs()
}
}
}
