pipeline {

  agent {
    docker {
      image 'maven:3.8.6-openjdk-11'
      args '-v /root/.m2:/root/.m2' //optional: to checkmaven dependencies
}
}
stages {
  stage('Checkout') {
    steps {
      git branch: 'main', 
        url: 'https://github.com/bimal-root/Jenkins-Zero-To-Hero.git'
} 
}
  stage('Verify') {
    steps {
      sh 'pwd && ls -l'
}
}

  stage('Build') {
    steps {
    // build mvn project
      dir('html-maven-project') {
        sh 'mvn clean package'
}
}
}
  stage('Run Jetty server') {
    steps {
   // start maven server to serve html file by using maven jetty plugin or Tomcat:
      dir('html-maven-project') {  
        sh 'mvn org.eclipse.jetty:jetty-maven-plugin:run'
}
}
}
}
post {
  always {
	// clean up
    cleanWs()
}
}
}
