pipeline {

  agent {
    docker {
      image 'maven:3.8.6-openjdk-11'
      args '-v /var/run/docker.sock:/var/run/docker.sock -p 80:80' // Map port 80 to the host
}
}
  environment {
    MAVEN_OPTS = '-Dmaven.test.skip=true' // Skip tests if not needed
}

stages {
  stage('Checkout') {
    steps {
      git branch: 'main', 
        url: 'https://github.com/bimal-root/Jenkins-Zero-To-Hero.git'
} 
}
  stage('Build') {
    steps {
    // build mvn project
      dir('html-maven-project') {
        sh 'mvn clean package'
}
}
}
  stage('Run Jetty server') {
    steps {
      // Start Jetty server with the WAR file on port 80

      dir('html-maven-project') {  
        sh 'java -jar target/dependency/jetty-runner.jar --port 80 target/html-maven-project.war'
}
}
}
}
}

